#!/bin/bash

TARGET="${1:-}"
DEBUG_EXTCFG="${2:-}"
MEMORY_EXTCFG="${3:-}"
TRACE_EXTCFG="${4:-}"
FEEDBACK_EXTCFG="${5:-}"
IMAGEBASE="${6:-}"
PATHLISTAPP="${7:-}"

export TARGET DEBUG_EXTCFG MEMORY_EXTCFG TRACE_EXTCFG FEEDBACK_EXTCFG IMAGEBASE PATHLISTAPP

source ./defaultenv.bash

export TARGET_IMG=${TARGET,,}

COMPILE_IMAGE="gen_compiler_$TARGET_IMG"
DOCKER_FILE_BUILD=dockerfile_build
GEN_PATH=../../..
BIND_MOUNT_GEN=../../$GEN_PATH/Projects:/Projects
BIND_MOUNT_CCACHE=/root/.cache/:/root/.cache/

bash -c "docker build --build-arg TARGET=$TARGET --build-arg IMAGEBASE=$IMAGEBASE --build-arg PATHLISTAPP=$PATHLISTAPP -t $COMPILE_IMAGE -f $GEN_PATH/Common/docker/$DOCKER_FILE_BUILD $GEN_PATH"                        
bash -c "docker run -it --rm --name gen_compiler_container -e TARGET=$TARGET -e DEBUG_EXTCFG=$DEBUG_EXTCFG -e MEMORY_EXTCFG=$MEMORY_EXTCFG -e TRACE_EXTCFG=$TRACE_EXTCFG -e FEEDBACK_EXTCFG=$FEEDBACK_EXTCFG -e IMAGEBASE=$IMAGEBASE -e PATHLISTAPP=$PATHLISTAPP -v $BIND_MOUNT_GEN -v $BIND_MOUNT_CCACHE $COMPILE_IMAGE"
