ARG IMAGEBASE
FROM ${IMAGEBASE:-debian}

ARG TARGET=INTEL32
ENV TARGET=${TARGET}

ARG DOCKERDOMAIN
ENV DOCKERDOMAIN=${DOCKERDOMAIN}

WORKDIR /install
COPY Common/scripts/linux_dependency_installers/ ./

RUN set -eux; \
    chmod +x "/install/install_build_$TARGET.sh"; \
    "/install/install_build_$TARGET.sh"; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /install

WORKDIR ${DOCKERDOMAIN}

ENTRYPOINT ["./compile.bash"]
CMD []
