ARG IMAGEBASE
FROM ${IMAGEBASE:-debian}

ARG TARGET=INTEL64
ENV TARGET=${TARGET}

ARG TARGET_LOWERCASE=intel64
ENV TARGET_LOWERCASE=${TARGET_LOWERCASE}

ARG DEBUG_EXTERNAL_CFG
ENV DEBUG_EXTERNAL_CFG=${DEBUG_EXTERNAL_CFG}

ARG APPPATH
ENV APPPATH=${APPPATH}

ARG APPNAME
ENV APPNAME=${APPNAME}

RUN apt-get update && \
    apt-get install -y --no-install-recommends bash \
libstdc++6 \
libc6 \
libatomic1 \
libasound2t64 \
libx11-6 \
libxext6 \
libxrandr2 \
libxxf86vm1 && \
printf 'pcm.!default { type null }\n' > /etc/asound.conf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ${APPPATH}/Platforms/Linux/${TARGET_LOWERCASE}/${DEBUG_EXTERNAL_CFG}/${APPNAME} .
COPY ${APPPATH}/assets .

CMD ["sh", "-c", "./${APPNAME}"]
