ARG IMAGEBASE
FROM ${IMAGEBASE:-debian}

ARG TARGET=INTEL32
ENV TARGET=${TARGET}

WORKDIR /install
COPY Common/scripts/linux_dependency_installers/ ./

RUN set -eux; \
    chmod +x "/install/install_dev_${TARGET}.sh"; \
    "/install/install_dev_${TARGET}.sh"; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /install

WORKDIR /Projects/GEN_FrameWork/Common/scripts/compile

CMD ["bash", "-c", "./compile_all_linux.bash \"$TARGET\" \"$DEBUG_EXTCFG\" \"$MEMORY_EXTCFG\" \"$TRACE_EXTCFG\" \"$FEEDBACK_EXTCFG\" \"$IMAGEBASE\" \"$PATHLISTAPP\""]

