ARG IMAGEBASE
FROM ${IMAGEBASE:-debian}

ARG TARGET
ENV TARGET=${TARGET}

WORKDIR /install
COPY Common/batch/linux_dependency_installers/  .     
RUN sh -c "chmod +x /install/install_${TARGET}.sh"
RUN sh -c "./install_${TARGET}.sh"

# RUN sh -c "chmod +x /install/*.sh"
# RUN sh -c "./install_INTEL64.sh"
# RUN sh -c "./install_ARM64.sh"

WORKDIR /Projects/GEN_FrameWork/Common/batch/compile

CMD ["sh", "-c", "./compile_all_linux.bash $TARGET $DEBUG_EXTCFG $MEMORY_EXTCFG $TRACE_EXTCFG $FEEDBACK_EXTCFG $IMAGEBASE $PATHCOMPILE"]

# CMD bash
