cmake_minimum_required(VERSION 3.16)

function(_gen_fail msg)
  message(FATAL_ERROR "[GEN Android] ${msg}")
endfunction()

function(_gen_strip_quotes in_var out_var)
  if(DEFINED ${in_var})
    set(_v "${${in_var}}")
  else()
    set(_v "")
  endif()
  string(STRIP "${_v}" _v)
  string(REGEX REPLACE "^\"(.*)\"$" "\\1" _v "${_v}")
  file(TO_CMAKE_PATH "${_v}" _v)
  set(${out_var} "${_v}" PARENT_SCOPE)
endfunction()

function(_gen_to_abs_value in_path base_dir out_var)
  set(_p "${in_path}")
  if(_p STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()
  file(TO_CMAKE_PATH "${_p}" _p)
  if(IS_ABSOLUTE "${_p}")
    set(_abs "${_p}")
  else()
    get_filename_component(_abs "${base_dir}/${_p}" ABSOLUTE)
    file(TO_CMAKE_PATH "${_abs}" _abs)
  endif()
  set(${out_var} "${_abs}" PARENT_SCOPE)
endfunction()

function(_gen_find_newest pattern_root pattern_glob out_var)
  if(NOT EXISTS "${pattern_root}")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()
  file(GLOB_RECURSE _matches LIST_DIRECTORIES false "${pattern_root}/${pattern_glob}")
  if(_matches)
    list(SORT _matches COMPARE NATURAL ORDER DESCENDING)
    list(GET _matches 0 _first)
    file(TO_CMAKE_PATH "${_first}" _first)
    set(${out_var} "${_first}" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

foreach(_var
  GEN_ANDROID_SOURCE_ASSETS_DIR
  GEN_ANDROID_GENERATED_MANIFEST
  GEN_ANDROID_NDK_ROOT
  GEN_ANDROID_SDK_ROOT
  GEN_ANDROID_JAVA_HOME
  GEN_ANDROID_ABI
  GEN_ANDROID_TARGET_SDK
  GEN_ANDROID_MIN_SDK
  GEN_ANDROID_PROJECT_NAME
  GEN_ANDROID_APP_ID
  GEN_ANDROID_APP_LABEL
  GEN_ANDROID_SHARED_LIBRARY
  GEN_ANDROID_OUTPUT_DIR)
  _gen_strip_quotes(${_var} ${_var}_CLEAN)
endforeach()

get_filename_component(_common_dir "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
get_filename_component(_framework_root "${_common_dir}/../.." ABSOLUTE)
file(TO_CMAKE_PATH "${_framework_root}" _framework_root)

if(GEN_ANDROID_OUTPUT_DIR_CLEAN STREQUAL "")
  _gen_fail("GEN_ANDROID_OUTPUT_DIR no está definido")
endif()
_gen_to_abs_value("${GEN_ANDROID_OUTPUT_DIR_CLEAN}" "${CMAKE_CURRENT_LIST_DIR}" _output_dir)
if(_output_dir STREQUAL "")
  _gen_fail("No se pudo resolver GEN_ANDROID_OUTPUT_DIR")
endif()

set(_build_work_dir "${_output_dir}")
_gen_to_abs_value("${GEN_ANDROID_SHARED_LIBRARY_CLEAN}"     "${_build_work_dir}" _shared_library)
_gen_to_abs_value("${GEN_ANDROID_SOURCE_ASSETS_DIR_CLEAN}"  "${_build_work_dir}" _assets_dir)
_gen_to_abs_value("${GEN_ANDROID_GENERATED_MANIFEST_CLEAN}" "${_build_work_dir}" _generated_manifest)
_gen_to_abs_value("${GEN_ANDROID_NDK_ROOT_CLEAN}"           "${_build_work_dir}" _ndk_root)
_gen_to_abs_value("${GEN_ANDROID_SDK_ROOT_CLEAN}"           "${_build_work_dir}" _sdk_root_input)

if(_shared_library STREQUAL "" OR NOT EXISTS "${_shared_library}")
  _gen_fail("Shared library not found:\n  ${_shared_library}")
endif()

if(GEN_ANDROID_PROJECT_NAME_CLEAN STREQUAL "")
  get_filename_component(GEN_ANDROID_PROJECT_NAME_CLEAN "${_shared_library}" NAME_WE)
  string(REGEX REPLACE "^lib" "" GEN_ANDROID_PROJECT_NAME_CLEAN "${GEN_ANDROID_PROJECT_NAME_CLEAN}")
endif()
if(GEN_ANDROID_APP_LABEL_CLEAN STREQUAL "")
  set(GEN_ANDROID_APP_LABEL_CLEAN "${GEN_ANDROID_PROJECT_NAME_CLEAN}")
endif()
if(GEN_ANDROID_APP_ID_CLEAN STREQUAL "")
  string(REGEX REPLACE "[^A-Za-z0-9_.]" "" _sanitized_id "${GEN_ANDROID_PROJECT_NAME_CLEAN}")
  if(_sanitized_id STREQUAL "")
    set(_sanitized_id "app")
  endif()
  set(GEN_ANDROID_APP_ID_CLEAN "com.gen.${_sanitized_id}")
endif()
if(GEN_ANDROID_TARGET_SDK_CLEAN STREQUAL "")
  set(GEN_ANDROID_TARGET_SDK_CLEAN "24")
endif()
if(GEN_ANDROID_MIN_SDK_CLEAN STREQUAL "")
  set(GEN_ANDROID_MIN_SDK_CLEAN "${GEN_ANDROID_TARGET_SDK_CLEAN}")
endif()
if(GEN_ANDROID_ABI_CLEAN STREQUAL "")
  set(GEN_ANDROID_ABI_CLEAN "arm64-v8a")
endif()

set(_real_sdk_root "${_sdk_root_input}")
if(_real_sdk_root STREQUAL "" OR NOT EXISTS "${_real_sdk_root}/platforms")
  if(EXISTS "${_framework_root}/ThirdPartyLibraries/android-sdk")
    set(_real_sdk_root "${_framework_root}/ThirdPartyLibraries/android-sdk")
  endif()
endif()
if(_real_sdk_root STREQUAL "" OR NOT EXISTS "${_real_sdk_root}")
  _gen_fail("No se encontró un Android SDK válido.\nSDK recibido: ${_sdk_root_input}")
endif()

if(_ndk_root STREQUAL "" OR NOT EXISTS "${_ndk_root}")
  if(EXISTS "${_framework_root}/ThirdPartyLibraries/android-ndk")
    set(_ndk_root "${_framework_root}/ThirdPartyLibraries/android-ndk")
  endif()
endif()

set(_android_jar "${_real_sdk_root}/platforms/android-${GEN_ANDROID_TARGET_SDK_CLEAN}/android.jar")
if(NOT EXISTS "${_android_jar}")
  _gen_fail("No se encontró android.jar:\n  ${_android_jar}")
endif()

_gen_find_newest("${_real_sdk_root}/build-tools" "*/aapt.exe" _aapt)
if(_aapt STREQUAL "")
  _gen_find_newest("${_real_sdk_root}/build-tools" "*/aapt2.exe" _aapt)
endif()
_gen_find_newest("${_real_sdk_root}/build-tools" "*/zipalign.exe" _zipalign)
_gen_find_newest("${_real_sdk_root}/build-tools" "*/apksigner.bat" _apksigner)
if(_apksigner STREQUAL "")
  _gen_find_newest("${_real_sdk_root}/build-tools" "*/apksigner" _apksigner)
endif()
if(_aapt STREQUAL "")
  _gen_fail("No se encontró aapt dentro de: ${_real_sdk_root}/build-tools")
endif()
if(_zipalign STREQUAL "")
  _gen_fail("No se encontró zipalign dentro de: ${_real_sdk_root}/build-tools")
endif()
if(_apksigner STREQUAL "")
  _gen_fail("No se encontró apksigner dentro de: ${_real_sdk_root}/build-tools")
endif()

message(STATUS "[GEN Android] Framework root : ${_framework_root}")
message(STATUS "[GEN Android] NDK root input : ${_ndk_root}")
message(STATUS "[GEN Android] SDK root input : ${_sdk_root_input}")
message(STATUS "[GEN Android] Output dir     : ${_output_dir}")
message(STATUS "[GEN Android] Shared library : ${_shared_library}")
message(STATUS "[GEN Android] Real SDK root   : ${_real_sdk_root}")
message(STATUS "[GEN Android] android.jar     : ${_android_jar}")
message(STATUS "[GEN Android] aapt           : ${_aapt}")
message(STATUS "[GEN Android] apksigner      : ${_apksigner}")
message(STATUS "[GEN Android] zipalign       : ${_zipalign}")

set(_package_dir "${_output_dir}/android_package")
set(_aapt_input_dir "${_output_dir}/android_aapt")
set(_aapt_res_dir "${_aapt_input_dir}/res")
set(_lib_dir "${_package_dir}/lib/${GEN_ANDROID_ABI_CLEAN}")
set(_manifest_path "${_generated_manifest}")
if(_manifest_path STREQUAL "")
  set(_manifest_path "${_package_dir}/AndroidManifest.xml")
endif()

file(REMOVE_RECURSE "${_package_dir}" "${_aapt_input_dir}")
file(MAKE_DIRECTORY "${_package_dir}")
file(MAKE_DIRECTORY "${_lib_dir}")
file(MAKE_DIRECTORY "${_aapt_res_dir}")
message(STATUS "[GEN Android] aapt input dir  : ${_aapt_input_dir}")

get_filename_component(_manifest_dir "${_manifest_path}" DIRECTORY)
file(MAKE_DIRECTORY "${_manifest_dir}")
file(WRITE  "${_manifest_path}" "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
file(APPEND "${_manifest_path}" "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n")
file(APPEND "${_manifest_path}" "    package=\"${GEN_ANDROID_APP_ID_CLEAN}\"\n")
file(APPEND "${_manifest_path}" "    android:versionCode=\"1\"\n")
file(APPEND "${_manifest_path}" "    android:versionName=\"1.0\">\n\n")
file(APPEND "${_manifest_path}" "    <uses-sdk android:minSdkVersion=\"${GEN_ANDROID_MIN_SDK_CLEAN}\" android:targetSdkVersion=\"${GEN_ANDROID_TARGET_SDK_CLEAN}\" />\n")
file(APPEND "${_manifest_path}" "    <uses-feature android:glEsVersion=\"0x00020000\" android:required=\"false\" />\n")
file(APPEND "${_manifest_path}" "    <application android:label=\"${GEN_ANDROID_APP_LABEL_CLEAN}\" android:hasCode=\"false\" android:extractNativeLibs=\"true\">\n")
file(APPEND "${_manifest_path}" "        <activity android:name=\"android.app.NativeActivity\" android:exported=\"true\" android:launchMode=\"singleTask\" android:configChanges=\"orientation|keyboardHidden|keyboard|navigation|screenLayout|screenSize|smallestScreenSize|uiMode|density|locale\" android:screenOrientation=\"landscape\">\n")
file(APPEND "${_manifest_path}" "            <intent-filter>\n")
file(APPEND "${_manifest_path}" "                <action android:name=\"android.intent.action.MAIN\" />\n")
file(APPEND "${_manifest_path}" "                <category android:name=\"android.intent.category.LAUNCHER\" />\n")
file(APPEND "${_manifest_path}" "            </intent-filter>\n")
file(APPEND "${_manifest_path}" "            <meta-data android:name=\"android.app.lib_name\" android:value=\"${GEN_ANDROID_PROJECT_NAME_CLEAN}\" />\n")
file(APPEND "${_manifest_path}" "        </activity>\n")
file(APPEND "${_manifest_path}" "    </application>\n")
file(APPEND "${_manifest_path}" "</manifest>\n")

file(COPY "${_shared_library}" DESTINATION "${_lib_dir}")

set(_libcpp "")
set(_ndk_triple "")
if(GEN_ANDROID_ABI_CLEAN STREQUAL "arm64-v8a")
  set(_ndk_triple "aarch64-linux-android")
elseif(GEN_ANDROID_ABI_CLEAN STREQUAL "armeabi-v7a")
  set(_ndk_triple "arm-linux-androideabi")
elseif(GEN_ANDROID_ABI_CLEAN STREQUAL "x86")
  set(_ndk_triple "i686-linux-android")
elseif(GEN_ANDROID_ABI_CLEAN STREQUAL "x86_64")
  set(_ndk_triple "x86_64-linux-android")
endif()

if(NOT _ndk_triple STREQUAL "")
  set(_libcpp_candidates
    "${_ndk_root}/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/${_ndk_triple}/libc++_shared.so"
    "${_ndk_root}/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/${_ndk_triple}/${GEN_ANDROID_MIN_SDK_CLEAN}/libc++_shared.so"
    "${_ndk_root}/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/${_ndk_triple}/${GEN_ANDROID_TARGET_SDK_CLEAN}/libc++_shared.so")
  foreach(_cand IN LISTS _libcpp_candidates)
    if(EXISTS "${_cand}")
      set(_libcpp "${_cand}")
      break()
    endif()
  endforeach()
endif()

if(_libcpp STREQUAL "")
  _gen_find_newest("${_ndk_root}" "*/${_ndk_triple}*/libc++_shared.so" _libcpp)
endif()
if(_libcpp STREQUAL "")
  _gen_find_newest("${_ndk_root}" "*/libc++_shared.so" _libcpp)
endif()
if(NOT _libcpp STREQUAL "")
  message(STATUS "[GEN Android] libc++_shared   : ${_libcpp}")
  file(COPY "${_libcpp}" DESTINATION "${_lib_dir}")
else()
  message(WARNING "[GEN Android] No se encontró libc++_shared.so. El APK puede cerrarse al abrir.")
endif()

set(_have_assets FALSE)
if(NOT _assets_dir STREQUAL "" AND EXISTS "${_assets_dir}")
  file(MAKE_DIRECTORY "${_package_dir}/assets")
  file(COPY "${_assets_dir}/" DESTINATION "${_package_dir}/assets")
  set(_have_assets TRUE)
endif()

set(_keystore_dir "${_output_dir}/debug_keystore")
set(_keystore "${_keystore_dir}/android-debug.keystore")
file(MAKE_DIRECTORY "${_keystore_dir}")
if(NOT EXISTS "${_keystore}")
  find_program(_keytool keytool)
  if(_keytool STREQUAL "_keytool-NOTFOUND")
    _gen_fail("No se encontró keytool en PATH para generar el debug keystore")
  endif()
  execute_process(
    COMMAND "${_keytool}" -genkeypair -noprompt -keystore "${_keystore}" -storepass android -keypass android -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
    RESULT_VARIABLE _keytool_res)
  if(NOT _keytool_res EQUAL 0)
    _gen_fail("No se pudo generar el debug keystore")
  endif()
endif()

set(_unaligned_apk "${_output_dir}/${GEN_ANDROID_PROJECT_NAME_CLEAN}-unaligned.apk")
set(_aligned_apk   "${_output_dir}/${GEN_ANDROID_PROJECT_NAME_CLEAN}-aligned.apk")
set(_final_apk     "${_output_dir}/${GEN_ANDROID_PROJECT_NAME_CLEAN}.apk")
set(_payload_zip   "${_package_dir}/payload.zip")
file(REMOVE "${_unaligned_apk}" "${_aligned_apk}" "${_final_apk}" "${_payload_zip}")

execute_process(
  COMMAND "${_aapt}" package -f -M "${_manifest_path}" -I "${_android_jar}" -F "${_unaligned_apk}" "${_aapt_input_dir}"
  RESULT_VARIABLE _aapt_res
  OUTPUT_VARIABLE _aapt_out
  ERROR_VARIABLE _aapt_err)
if(NOT _aapt_res EQUAL 0)
  message(STATUS "${_aapt_out}")
  message(STATUS "${_aapt_err}")
  _gen_fail("aapt package falló")
endif()

set(_merge_ps1 "${_package_dir}/merge_payload.ps1")
file(WRITE  "${_merge_ps1}" "Add-Type -AssemblyName System.IO.Compression\n")
file(APPEND "${_merge_ps1}" "Add-Type -AssemblyName System.IO.Compression.FileSystem\n")
file(APPEND "${_merge_ps1}" "$apk = [System.IO.Path]::GetFullPath('${_unaligned_apk}')\n")
file(APPEND "${_merge_ps1}" "$pkg = [System.IO.Path]::GetFullPath('${_package_dir}')\n")
file(APPEND "${_merge_ps1}" "$zip = [System.IO.Compression.ZipFile]::Open($apk, [System.IO.Compression.ZipArchiveMode]::Update)\n")
file(APPEND "${_merge_ps1}" "try {\n")
file(APPEND "${_merge_ps1}" "  $pkgRoot = [System.IO.Path]::GetFullPath($pkg)\n")
file(APPEND "${_merge_ps1}" "  $pkgRootWithSep = $pkgRoot\n")
file(APPEND "${_merge_ps1}" "  if(-not $pkgRootWithSep.EndsWith([System.IO.Path]::DirectorySeparatorChar)) { $pkgRootWithSep += [System.IO.Path]::DirectorySeparatorChar }\n")
file(APPEND "${_merge_ps1}" "  $entries = @()\n")
file(APPEND "${_merge_ps1}" "  if(Test-Path (Join-Path $pkg 'lib')) { $entries += Get-ChildItem -Path (Join-Path $pkg 'lib') -Recurse -File }\n")
file(APPEND "${_merge_ps1}" "  if(Test-Path (Join-Path $pkg 'assets')) { $entries += Get-ChildItem -Path (Join-Path $pkg 'assets') -Recurse -File }\n")
file(APPEND "${_merge_ps1}" "  foreach($f in $entries) {\n")
file(APPEND "${_merge_ps1}" "    $full = [System.IO.Path]::GetFullPath($f.FullName)\n")
file(APPEND "${_merge_ps1}" "    if(-not $full.StartsWith($pkgRootWithSep)) { throw 'Entry fuera del directorio de paquete: ' + $full }\n")
file(APPEND "${_merge_ps1}" "    $rel = $full.Substring($pkgRootWithSep.Length).Replace('\\','/')\n")
file(APPEND "${_merge_ps1}" "    $existing = $zip.GetEntry($rel)\n")
file(APPEND "${_merge_ps1}" "    if($existing -ne $null) { $existing.Delete() }\n")
file(APPEND "${_merge_ps1}" "    $level = [System.IO.Compression.CompressionLevel]::Optimal\n")
file(APPEND "${_merge_ps1}" "    if($rel.StartsWith('lib/')) { $level = [System.IO.Compression.CompressionLevel]::NoCompression }\n")
file(APPEND "${_merge_ps1}" "    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $full, $rel, $level) | Out-Null\n")
file(APPEND "${_merge_ps1}" "  }\n")
file(APPEND "${_merge_ps1}" "}\n")
file(APPEND "${_merge_ps1}" "finally { if($zip -ne $null) { $zip.Dispose() } }\n")

find_program(_powershell_exec NAMES powershell pwsh REQUIRED)
execute_process(
  COMMAND "${_powershell_exec}" -NoProfile -ExecutionPolicy Bypass -File "${_merge_ps1}"
  RESULT_VARIABLE _merge_res
  OUTPUT_VARIABLE _merge_out
  ERROR_VARIABLE _merge_err)
if(NOT _merge_res EQUAL 0)
  message(STATUS "${_merge_out}")
  message(STATUS "${_merge_err}")
  _gen_fail("No se pudo insertar lib/ y assets/ en el APK")
endif()
execute_process(
  COMMAND "${_zipalign}" -f 4 "${_unaligned_apk}" "${_aligned_apk}"
  RESULT_VARIABLE _zipalign_res
  OUTPUT_VARIABLE _zipalign_out
  ERROR_VARIABLE _zipalign_err)
if(NOT _zipalign_res EQUAL 0)
  message(STATUS "${_zipalign_out}")
  message(STATUS "${_zipalign_err}")
  _gen_fail("zipalign falló")
endif()

execute_process(
  COMMAND "${_apksigner}" sign --ks "${_keystore}" --ks-pass pass:android --key-pass pass:android --out "${_final_apk}" "${_aligned_apk}"
  RESULT_VARIABLE _sign_res
  OUTPUT_VARIABLE _sign_out
  ERROR_VARIABLE _sign_err)
if(NOT _sign_res EQUAL 0)
  message(STATUS "${_sign_out}")
  message(STATUS "${_sign_err}")
  _gen_fail("apksigner falló")
endif()

message(STATUS "[GEN Android] APK generado correctamente: ${_final_apk}")
