cmake_minimum_required(VERSION 3.16)

include_guard(GLOBAL)

function(_gen_strip_quotes VAR_NAME)
  if(DEFINED ${VAR_NAME})
    set(_v "${${VAR_NAME}}")
    string(STRIP "${_v}" _v)
    string(REGEX REPLACE "^\"(.*)\"$" "\\1" _v "${_v}")
    set(${VAR_NAME} "${_v}" PARENT_SCOPE)
  endif()
endfunction()

function(_gen_to_cmake_path VAR_NAME)
  if(DEFINED ${VAR_NAME} AND NOT "${${VAR_NAME}}" STREQUAL "")
    file(TO_CMAKE_PATH "${${VAR_NAME}}" _v)
    set(${VAR_NAME} "${_v}" PARENT_SCOPE)
  endif()
endfunction()

get_filename_component(_GEN_COMMON_DIR "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
get_filename_component(_GEN_FRAMEWORK_ROOT "${_GEN_COMMON_DIR}" DIRECTORY)
file(TO_CMAKE_PATH "${_GEN_FRAMEWORK_ROOT}" _GEN_FRAMEWORK_ROOT)

if(NOT DEFINED GEN_ANDROID_TARGET_NAME OR "${GEN_ANDROID_TARGET_NAME}" STREQUAL "")
  if(TARGET "${CMAKE_PROJECT_NAME}")
    set(GEN_ANDROID_TARGET_NAME "${CMAKE_PROJECT_NAME}")
  elseif(TARGET "${PROJECT_NAME}")
    set(GEN_ANDROID_TARGET_NAME "${PROJECT_NAME}")
  else()
    set(GEN_ANDROID_TARGET_NAME "${CMAKE_PROJECT_NAME}")
  endif()
endif()

if(NOT DEFINED GEN_ANDROID_PROJECT_NAME OR "${GEN_ANDROID_PROJECT_NAME}" STREQUAL "")
  if(DEFINED APP_PROJECT_NAME AND NOT "${APP_PROJECT_NAME}" STREQUAL "")
    set(GEN_ANDROID_PROJECT_NAME "${APP_PROJECT_NAME}")
  elseif(NOT "${GEN_ANDROID_TARGET_NAME}" STREQUAL "")
    set(GEN_ANDROID_PROJECT_NAME "${GEN_ANDROID_TARGET_NAME}")
  elseif(NOT "${PROJECT_NAME}" STREQUAL "")
    set(GEN_ANDROID_PROJECT_NAME "${PROJECT_NAME}")
  else()
    get_filename_component(GEN_ANDROID_PROJECT_NAME "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
  endif()
endif()

if(NOT DEFINED GEN_ANDROID_ABI OR "${GEN_ANDROID_ABI}" STREQUAL "")
  if(DEFINED ANDROID_ABI AND NOT "${ANDROID_ABI}" STREQUAL "")
    set(GEN_ANDROID_ABI "${ANDROID_ABI}")
  elseif(DEFINED CMAKE_ANDROID_ARCH_ABI AND NOT "${CMAKE_ANDROID_ARCH_ABI}" STREQUAL "")
    set(GEN_ANDROID_ABI "${CMAKE_ANDROID_ARCH_ABI}")
  else()
    set(GEN_ANDROID_ABI "arm64-v8a")
  endif()
endif()

if(NOT DEFINED GEN_ANDROID_TARGET_SDK OR "${GEN_ANDROID_TARGET_SDK}" STREQUAL "")
  if(DEFINED ANDROID_PLATFORM AND NOT "${ANDROID_PLATFORM}" STREQUAL "")
    string(REGEX REPLACE "^android-" "" GEN_ANDROID_TARGET_SDK "${ANDROID_PLATFORM}")
  else()
    set(GEN_ANDROID_TARGET_SDK "24")
  endif()
endif()

if(NOT DEFINED GEN_ANDROID_MIN_SDK OR "${GEN_ANDROID_MIN_SDK}" STREQUAL "")
  set(GEN_ANDROID_MIN_SDK "${GEN_ANDROID_TARGET_SDK}")
endif()

if(NOT DEFINED GEN_ANDROID_OUTPUT_DIR OR "${GEN_ANDROID_OUTPUT_DIR}" STREQUAL "")
  set(GEN_ANDROID_OUTPUT_DIR "${CMAKE_BINARY_DIR}")
endif()

if(NOT DEFINED GEN_ANDROID_SOURCE_ASSETS_DIR OR "${GEN_ANDROID_SOURCE_ASSETS_DIR}" STREQUAL "")
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/../assets")
    set(GEN_ANDROID_SOURCE_ASSETS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../assets")
  elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/assets")
    set(GEN_ANDROID_SOURCE_ASSETS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/assets")
  else()
    set(GEN_ANDROID_SOURCE_ASSETS_DIR "")
  endif()
endif()

if(NOT DEFINED GEN_ANDROID_GENERATED_MANIFEST OR "${GEN_ANDROID_GENERATED_MANIFEST}" STREQUAL "")
  set(GEN_ANDROID_GENERATED_MANIFEST "${GEN_ANDROID_OUTPUT_DIR}/android_package/AndroidManifest.xml")
endif()

if(NOT DEFINED GEN_ANDROID_JAVA_HOME)
  set(GEN_ANDROID_JAVA_HOME "")
endif()

if(NOT DEFINED GEN_ANDROID_NDK_ROOT OR "${GEN_ANDROID_NDK_ROOT}" STREQUAL "")
  set(_GEN_NDK_ABS "${_GEN_FRAMEWORK_ROOT}/ThirdPartyLibraries/android-ndk")
  file(RELATIVE_PATH GEN_ANDROID_NDK_ROOT "${GEN_ANDROID_OUTPUT_DIR}" "${_GEN_NDK_ABS}")
endif()

if(NOT DEFINED GEN_ANDROID_SDK_ROOT OR "${GEN_ANDROID_SDK_ROOT}" STREQUAL "")
  set(_GEN_SDK_ABS "${_GEN_FRAMEWORK_ROOT}/ThirdPartyLibraries/android-sdk")
  file(RELATIVE_PATH GEN_ANDROID_SDK_ROOT "${GEN_ANDROID_OUTPUT_DIR}" "${_GEN_SDK_ABS}")
endif()

if(NOT DEFINED GEN_ANDROID_APP_ID OR "${GEN_ANDROID_APP_ID}" STREQUAL "")
  set(GEN_ANDROID_APP_ID "com.gen.${GEN_ANDROID_PROJECT_NAME}")
endif()

if(NOT DEFINED GEN_ANDROID_APP_LABEL OR "${GEN_ANDROID_APP_LABEL}" STREQUAL "")
  set(GEN_ANDROID_APP_LABEL "${GEN_ANDROID_PROJECT_NAME}")
endif()

if(NOT DEFINED GEN_ANDROID_SHARED_LIBRARY OR "${GEN_ANDROID_SHARED_LIBRARY}" STREQUAL "")
  if(TARGET "${GEN_ANDROID_TARGET_NAME}")
    set(GEN_ANDROID_SHARED_LIBRARY "$<TARGET_FILE:${GEN_ANDROID_TARGET_NAME}>")
  else()
    set(GEN_ANDROID_SHARED_LIBRARY "${GEN_ANDROID_OUTPUT_DIR}/lib${GEN_ANDROID_PROJECT_NAME}.so")
  endif()
endif()

foreach(_var
  GEN_ANDROID_TARGET_NAME
  GEN_ANDROID_PROJECT_NAME
  GEN_ANDROID_ABI
  GEN_ANDROID_TARGET_SDK
  GEN_ANDROID_MIN_SDK
  GEN_ANDROID_OUTPUT_DIR
  GEN_ANDROID_SOURCE_ASSETS_DIR
  GEN_ANDROID_GENERATED_MANIFEST
  GEN_ANDROID_JAVA_HOME
  GEN_ANDROID_NDK_ROOT
  GEN_ANDROID_SDK_ROOT
  GEN_ANDROID_APP_ID
  GEN_ANDROID_APP_LABEL
  GEN_ANDROID_SHARED_LIBRARY)
  _gen_strip_quotes(${_var})
endforeach()

foreach(_var
  GEN_ANDROID_OUTPUT_DIR
  GEN_ANDROID_SOURCE_ASSETS_DIR
  GEN_ANDROID_GENERATED_MANIFEST
  GEN_ANDROID_JAVA_HOME
  GEN_ANDROID_NDK_ROOT
  GEN_ANDROID_SDK_ROOT)
  _gen_to_cmake_path(${_var})
endforeach()

set(_GEN_ANDROID_BUILD_SCRIPT "${_GEN_FRAMEWORK_ROOT}/Common/cmake/GEN_AndroidPackage_Build.cmake")
file(TO_CMAKE_PATH "${_GEN_ANDROID_BUILD_SCRIPT}" _GEN_ANDROID_BUILD_SCRIPT)

if(NOT EXISTS "${_GEN_ANDROID_BUILD_SCRIPT}")
  message(FATAL_ERROR "[GEN Android] No se encuentra el script de build: ${_GEN_ANDROID_BUILD_SCRIPT}")
endif()

if(NOT TARGET "${GEN_ANDROID_TARGET_NAME}")
  message(FATAL_ERROR "[GEN Android] No existe el target '${GEN_ANDROID_TARGET_NAME}' al incluir GEN_AndroidPackage.cmake")
endif()

message(STATUS "[GEN Android] Project name     : ${GEN_ANDROID_PROJECT_NAME}")
message(STATUS "[GEN Android] ABI              : ${GEN_ANDROID_ABI}")
message(STATUS "[GEN Android] Target SDK       : ${GEN_ANDROID_TARGET_SDK}")
message(STATUS "[GEN Android] Output dir       : ${GEN_ANDROID_OUTPUT_DIR}")
message(STATUS "[GEN Android] NDK root (input) : ${GEN_ANDROID_NDK_ROOT}")
message(STATUS "[GEN Android] SDK root (input) : ${GEN_ANDROID_SDK_ROOT}")
message(STATUS "[GEN Android] Shared library   : ${GEN_ANDROID_SHARED_LIBRARY}")

set(_GEN_ANDROID_POST_BUILD_GUARD "GEN_ANDROID_POST_BUILD_ADDED_${GEN_ANDROID_TARGET_NAME}")
get_property(_gen_post_build_added GLOBAL PROPERTY "${_GEN_ANDROID_POST_BUILD_GUARD}")
if(NOT _gen_post_build_added)
  set_property(GLOBAL PROPERTY "${_GEN_ANDROID_POST_BUILD_GUARD}" TRUE)

  add_custom_command(
    TARGET "${GEN_ANDROID_TARGET_NAME}" POST_BUILD
    COMMAND "${CMAKE_COMMAND}"
      "-DGEN_ANDROID_SOURCE_ASSETS_DIR=${GEN_ANDROID_SOURCE_ASSETS_DIR}"
      "-DGEN_ANDROID_GENERATED_MANIFEST=${GEN_ANDROID_GENERATED_MANIFEST}"
      "-DGEN_ANDROID_NDK_ROOT=${GEN_ANDROID_NDK_ROOT}"
      "-DGEN_ANDROID_SDK_ROOT=${GEN_ANDROID_SDK_ROOT}"
      "-DGEN_ANDROID_JAVA_HOME=${GEN_ANDROID_JAVA_HOME}"
      "-DGEN_ANDROID_ABI=${GEN_ANDROID_ABI}"
      "-DGEN_ANDROID_TARGET_SDK=${GEN_ANDROID_TARGET_SDK}"
      "-DGEN_ANDROID_MIN_SDK=${GEN_ANDROID_MIN_SDK}"
      "-DGEN_ANDROID_PROJECT_NAME=${GEN_ANDROID_PROJECT_NAME}"
      "-DGEN_ANDROID_APP_ID=${GEN_ANDROID_APP_ID}"
      "-DGEN_ANDROID_APP_LABEL=${GEN_ANDROID_APP_LABEL}"
      "-DGEN_ANDROID_SHARED_LIBRARY=${GEN_ANDROID_SHARED_LIBRARY}"
      "-DGEN_ANDROID_OUTPUT_DIR=${GEN_ANDROID_OUTPUT_DIR}"
      -P "${_GEN_ANDROID_BUILD_SCRIPT}"
    VERBATIM
    COMMENT "Generate Android APK for ${GEN_ANDROID_PROJECT_NAME}"
  )
endif()

set(_GEN_ANDROID_APK_TARGET "${GEN_ANDROID_PROJECT_NAME}_apk")
if(NOT TARGET "${_GEN_ANDROID_APK_TARGET}")
  add_custom_target("${_GEN_ANDROID_APK_TARGET}" DEPENDS "${GEN_ANDROID_TARGET_NAME}")
endif()
