# --------------------------------------------------------------------
# GEN_Main_Sources_Android.cmake
# Main: Sources Android
# --------------------------------------------------------------------

 
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/ANDROIDJNI.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/ANDROIDJNIObject.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/ANDROIDNativeActivity.cpp")  

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/MainProcANDROID.cpp")

 
if(GRP_FEATURE)  

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/GRPANDROIDFactory.cpp")    
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/GRPANDROIDScreen.cpp")    
  
endif()


if(INP_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/INPANDROIDFactory.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/INPANDROIDDeviceKeyboard.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/INPANDROIDDeviceMouse.cpp")

endif()


if(SND_FEATURE)
  
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/SNDANDROIDFactory.cpp")
      
endif()


if(DIO_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDFactory.cpp")

endif()


if(DIO_PING_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDPing.cpp")

endif()


if(DIO_STREAMUART_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamUART.cpp")  
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamUARTLocalEnumDevices.cpp")

endif()


if(DIO_STREAMUSB_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamUSB.cpp")  
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamUSBLocalEnumDevices.cpp")

endif()


if(DIO_STREAMI2C_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamI2C.cpp")    

endif()


if(DIO_STREAMSPI_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamSPI.cpp")    

endif()


if(DIO_STREAMICMP_FEATURE)
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamICMP.cpp")
endif()


if(DIO_STREAMUDP_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamUDP.cpp")  
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamIPLocalEnumDevices.cpp")  

endif()


if(DIO_STREAMTCPIP_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamTCPIP.cpp") 
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/DIOLINUXStreamTCPIP.cpp") 
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamIPLocalEnumDevices.cpp")

endif()


if(DIO_STREAMBLUETOOTH_FEATURE OR DIO_STREAMBLUETOOTHLE_FEATURE)            

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamBluetooth.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamBluetoothLocalEnumDevices.cpp")      

endif()


if(DIO_STREAMBLUETOOTH_FEATURE)            

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamBluetoothRemoteEnumDevices.cpp")

endif()


if(DIO_STREAMBLUETOOTHLE_FEATURE)            

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamBluetoothLERemoteEnumDevices.cpp")

endif()


if(DIO_STREAMWIFI_FEATURE)        

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDStreamWifiRemoteEnumDevices.cpp")

endif()


if(DIO_WIFIMANAGERMODE_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDWifiManagerMode.cpp")

endif()


if(DIO_PCAP_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/DIOANDROIDPCap.cpp")      

endif()


list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDFactory.cpp")

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDTrace.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXTrace.cpp")

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDTimer.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXTimer.cpp")

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDRand.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXRand.cpp")

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDDir.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXDir.cpp")

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDThread.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXThread.cpp")

list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDDateTime.cpp")
list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXDateTime.cpp")


if(XSYSTEM_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDSystem.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXSystem.cpp")

endif()


if(XSLEEP_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDSleep.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXSleep.cpp")

endif()


if(XCONSOLE_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDConsole.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLinuxConsole.cpp")

endif()


if(XFILE_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDFile.cpp")
  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_LINUX}/XLINUXFile.cpp")

endif()


if(XPROCESSMANAGER_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDProcessManager.cpp")

endif()


if(XSHAREDMEMORYMANAGER_FEATURE)

  list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_SOURCES_PLATFORMS_ANDROID}/XANDROIDSharedMemoryManager.cpp")

endif()

