# --------------------------------------------------------------------
# GEN_Main_Sources_ThirdPartyLibraries.cmake
# Main: Sources Third Party Libraries
# --------------------------------------------------------------------


if(XFILE_ZIP_FEATURE)

  list(APPEND GEN_THIRDPARTY_LIBRARYS ZLib)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/adler32.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/compress.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/crc32.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/deflate.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/infback.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/inffast.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/inflate.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/inftrees.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/trees.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/uncompr.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB}/zutil.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB_MINIZIP}/ioapi.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB_MINIZIP}/unzip.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_ZLIB_MINIZIP}/zip.c")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(ZLib ${GEN_TPL_SOURCES})

endif()


if(GEN_SOURCES_MODULES_LIST MATCHES "DIOLINUXLedNeoPixelWS2812BRPi.cpp")

  list(APPEND GEN_THIRDPARTY_LIBRARYS RPI_WS281X)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_RPI_WS281X}/mailbox.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_RPI_WS281X}/ws2811.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_RPI_WS281X}/pwm.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_RPI_WS281X}/pcm.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_RPI_WS281X}/dma.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_RPI_WS281X}/rpihw.c")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(RPI_WS281X ${GEN_TPL_SOURCES})

endif()


if(GRP_2D_FEATURE)

  # AGG

  list(APPEND GEN_THIRDPARTY_LIBRARYS AGG)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_arc.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_arrowhead.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_bezier_arc.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_bspline.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_curves.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_embedded_raster_fonts.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_gsv_text.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_image_filters.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_line_aa_basics.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_line_profile_aa.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_rounded_rect.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_sqrt_tables.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_trans_affine.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_trans_double_path.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_trans_single_path.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_trans_warp_magnifier.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vcgen_bspline.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vcgen_contour.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vcgen_dash.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vcgen_markers_term.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vcgen_smooth_poly1.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vcgen_stroke.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vpgen_clip_polygon.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vpgen_clip_polyline.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_SOURCES}/agg_vpgen_segmentator.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_AGG_FREETYPE}/agg_font_freetype.cpp")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(AGG ${GEN_TPL_SOURCES})


  # FreeType
  # FT_MODULES

  list(APPEND GEN_THIRDPARTY_LIBRARYS FreeType)

  #add_definitions(-DFT_CONFIG_OPTION_FORCE_INT64)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftbbox.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftbdf.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftbitmap.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftcid.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftfstype.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftgasp.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftglyph.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftgxval.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftmm.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftotval.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftpatent.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftpfr.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftstroke.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftsynth.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/fttype1.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftwinfnt.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/autofit/autofit.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftbase.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/cache/ftccache.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftdebug.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/bdf/bdf.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/gzip/ftgzip.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/cff/cff.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftinit.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/lzw/ftlzw.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/base/ftsystem.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/pcf/pcf.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/pfr/pfr.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/psaux/psaux.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/pshinter/pshinter.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/psnames/psmodule.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/raster/raster.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/sfnt/sfnt.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/smooth/smooth.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/truetype/truetype.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/type1/type1.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/cid/type1cid.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/type42/type42.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/winfonts/winfnt.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/cache/ftcmru.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/cache/ftcmanag.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/sdf/sdf.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_FREETYPE_SOURCES}/svg/svg.c")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(FreeType ${GEN_TPL_SOURCES})

endif()


if(GRP_BITMAP_FILE_JPG_FEATURE)

  list(APPEND GEN_THIRDPARTY_LIBRARYS JPEGLib)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jaricom.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcapimin.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcapistd.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcarith.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jccoefct.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jccolor.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcdctmgr.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jchuff.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcinit.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcmainct.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcmarker.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcmaster.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcomapi.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcparam.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcprepct.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jcsample.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jctrans.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdapimin.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdapistd.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdarith.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdatadst.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdatasrc.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdcoefct.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdcolor.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jddctmgr.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdhuff.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdinput.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdmainct.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdmarker.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdmaster.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdmerge.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdpostct.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdsample.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jdtrans.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jerror.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jfdctflt.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jfdctfst.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jfdctint.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jidctflt.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jidctfst.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jidctint.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jmemmgr.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jmemnobs.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jquant1.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jquant2.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_JPEGLIB}/jutils.c")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(JPEGLib ${GEN_TPL_SOURCES})

endif()


if(GRP_BITMAP_FILE_PNG_FEATURE)

  list(APPEND GEN_THIRDPARTY_LIBRARYS LibPNG)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/png.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngerror.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngget.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngmem.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngpread.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngread.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngrio.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngrtran.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngrutil.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngset.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngtrans.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngwio.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngwrite.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngwtran.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/pngwutil.c")

  if(COMPILE_FOR_LINUX_ARM_RPI OR COMPILE_FOR_LINUX_ARM OR COMPILE_FOR_LINUX_ARM_RPI_64 OR COMPILE_FOR_LINUX_ARM_64 OR COMPILE_FOR_ANDROID)

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/arm/arm_init.c")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/arm/palette_neon_intrinsics.c")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LIBPNG}/arm/filter_neon_intrinsics.c")

  endif()

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(LibPNG ${GEN_TPL_SOURCES})

endif()


if(SCRIPT_LUA_FEATURE)

  #add_definitions(-DLUA_USE_POSIX)

  if(COMPILE_FOR_LINUX)

    add_definitions(-DLUA_USE_MKSTEMP)

  endif()

  list(APPEND GEN_THIRDPARTY_LIBRARYS LUA)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lapi.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lauxlib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lbaselib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lbitlib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lcode.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lcorolib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lctype.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ldblib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ldebug.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ldo.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ldump.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lfunc.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lgc.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/linit.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/liolib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/llex.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lmathlib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lmem.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/loadlib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lobject.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lopcodes.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/loslib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lparser.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lstate.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lstring.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lstrlib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ltable.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ltablib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/ltm.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lundump.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lutf8lib.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lvm.c")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_LUA}/lzio.c")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(LUA ${GEN_TPL_SOURCES})

endif()


if(SCRIPT_JAVASCRIPT_FEATURE)

  list(APPEND GEN_THIRDPARTY_LIBRARYS DuckTape)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_DUKTAPE}/duktape.c")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(DuckTape ${GEN_TPL_SOURCES})

endif()



if(SND_FEATURE)  
  
  list(APPEND GEN_THIRDPARTY_LIBRARYS OpenAL)

  set(CMAKE_CXX_STANDARD 17)

  add_definitions(-DAL_LIBTYPE_STATIC)
  add_definitions(-DAL_BUILD_LIBRARY)

  add_definitions(-DALC_API=)
  add_definitions(-DAL_API=)

  add_definitions(-DNOMINMAX)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)  
  add_definitions(-DRESTRICT=__restrict) 
  add_definitions(-DAL_ALEXT_PROTOTYPES)
  add_definitions(-DCMAKE_INTDIR="Debug")
  add_definitions(-DOpenAL_EXPORTS)
  add_definitions(-DFMT_HEADER_ONLY)

  if(IS_ABSOLUTE "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}")
    set(_GEN_OPENAL_TEMPLATES_DIR "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}")
  else()
    get_filename_component(_GEN_OPENAL_TEMPLATES_DIR "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()

  set(_GEN_OPENAL_GENERATED_DIR             "${_GEN_OPENAL_TEMPLATES_DIR}/generated")
  set(_GEN_OPENAL_GENERATED_PLATFORM_DIR    "")
  set(_GEN_OPENAL_ANDROID_ABI               "")

  if(NOT EXISTS "${_GEN_OPENAL_TEMPLATES_DIR}/config.h.in")
    message(FATAL_ERROR "[ GEN OpenAL] OpenAL Soft 1.24.3 templates were not found in ${_GEN_OPENAL_TEMPLATES_DIR}. Replace ThirdPartyLibraries/openal-soft with OpenAL Soft 1.24.3 before configuring.")
  endif()

  set(ALSOFT_FORCE_ALIGN "")

  unset(ALSOFT_EMBED_HRTF_DATA)
  unset(HAVE_PROC_PIDPATH)
  unset(HAVE_DLFCN_H)
  unset(HAVE_PTHREAD_NP_H)
  unset(HAVE_CPUID_H)
  unset(HAVE_INTRIN_H)
  unset(HAVE_GUIDDEF_H)
  unset(HAVE_GCC_GET_CPUID)
  unset(HAVE_CPUID_INTRINSIC)
  unset(HAVE_PTHREAD_SETSCHEDPARAM)
  unset(HAVE_PTHREAD_SETNAME_NP)
  unset(HAVE_PTHREAD_SET_NAME_NP)
  unset(ALSOFT_INSTALL_DATADIR)

  set(HAVE_RTKIT          0)
  set(ALSOFT_UWP          0)
  set(ALSOFT_EAX          0)

  set(HAVE_ALSA           0)
  set(HAVE_OSS            0)
  set(HAVE_PIPEWIRE       0)
  set(HAVE_SOLARIS        0)
  set(HAVE_SNDIO          0)
  set(HAVE_WASAPI         0)
  set(HAVE_DSOUND         0)
  set(HAVE_WINMM          0)
  set(HAVE_PORTAUDIO      0)
  set(HAVE_PULSEAUDIO     0)
  set(HAVE_JACK           0)
  set(HAVE_COREAUDIO      0)
  set(HAVE_OPENSL         0)
  set(HAVE_OBOE           0)
  set(HAVE_OTHERIO        0)
  set(HAVE_WAVE           0)
  set(HAVE_SDL3           0)
  set(HAVE_SDL2           0)

  set(HAVE_SSE            0)
  set(HAVE_SSE2           0)
  set(HAVE_SSE3           0)
  set(HAVE_SSE4_1         0)
  set(HAVE_SSE_INTRINSICS 0)
  set(HAVE_NEON           0)

  set(LIB_VERSION         "1.24.3")
  set(LIB_VERSION_NUM     "1,24,3,0")
  set(GIT_BRANCH          "UNKNOWN")
  set(GIT_COMMIT_HASH     "unknown")

  if(COMPILE_FOR_WINDOWS)  
 
    add_definitions(-DWIN32)
    add_definitions(-D_WIN32)
    add_definitions(-D_WINDOWS)
    add_definitions(-DWINDOWS)

    if(COMPILE_FOR_WINDOWS_INTEL_32)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/windows/intel32")
    endif()

    if(COMPILE_FOR_WINDOWS_INTEL_64)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/windows/intel64")
    endif()

    set(HAVE_INTRIN_H          1)
    set(HAVE_GUIDDEF_H         1)
    set(HAVE_CPUID_INTRINSIC   1)

    set(ALSOFT_EAX             1)

    set(HAVE_WASAPI            1)
    set(HAVE_DSOUND            1)
    set(HAVE_WINMM             1)
    set(HAVE_WAVE              1)

    set(HAVE_SSE               1)
    set(HAVE_SSE2              1)
    set(HAVE_SSE3              1)
    set(HAVE_SSE4_1            1)
    set(HAVE_SSE_INTRINSICS    1)

  endif()

  if(COMPILE_FOR_LINUX)  

    if(COMPILE_FOR_LINUX_INTEL_64)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/linux/intel64")

      set(HAVE_CPUID_H          1)
      set(HAVE_GCC_GET_CPUID    1)

      set(HAVE_SSE              1)
      set(HAVE_SSE2             1)
      set(HAVE_SSE3             1)
      set(HAVE_SSE4_1           1)
      set(HAVE_SSE_INTRINSICS   1)
    endif()

    if(COMPILE_FOR_LINUX_ARM)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/linux/arm32")
    endif()

    if(COMPILE_FOR_LINUX_ARM_64)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/linux/arm64")
      set(HAVE_NEON 1)
    endif()

    if(COMPILE_FOR_LINUX_ARM_RPI)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/linux/rpi32")
    endif()

    if(COMPILE_FOR_LINUX_ARM_RPI_64)
      set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/linux/rpi64")
      set(HAVE_NEON 1)
    endif()

    set(HAVE_DLFCN_H              1)
    set(HAVE_PTHREAD_SETSCHEDPARAM 1)
    set(HAVE_PTHREAD_SETNAME_NP   1)

    set(HAVE_RTKIT                1)

    set(HAVE_ALSA                 1)
    set(HAVE_OSS                  1)
    set(HAVE_PULSEAUDIO           1)
    set(HAVE_WAVE                 1)

  endif()

  if(COMPILE_FOR_ANDROID)

    if(DEFINED ANDROID_ABI AND NOT "${ANDROID_ABI}" STREQUAL "")
      set(_GEN_OPENAL_ANDROID_ABI "${ANDROID_ABI}")
    elseif(DEFINED GEN_ANDROID_ABI AND NOT "${GEN_ANDROID_ABI}" STREQUAL "")
      set(_GEN_OPENAL_ANDROID_ABI "${GEN_ANDROID_ABI}")
    else()
      set(_GEN_OPENAL_ANDROID_ABI "arm64-v8a")
    endif()

    set(_GEN_OPENAL_GENERATED_PLATFORM_DIR "${_GEN_OPENAL_GENERATED_DIR}/android/${_GEN_OPENAL_ANDROID_ABI}")

    set(HAVE_DLFCN_H                1)
    set(HAVE_PTHREAD_SETNAME_NP     1)
    set(HAVE_PTHREAD_SETSCHEDPARAM  1)

    set(HAVE_OPENSL                 1)
    set(HAVE_WAVE                   1)

    if(_GEN_OPENAL_ANDROID_ABI STREQUAL "x86")
      set(HAVE_SSE                  1)
      set(HAVE_SSE2                 1)
      set(HAVE_SSE3                 1)
      set(HAVE_SSE4_1               1)
      set(HAVE_SSE_INTRINSICS       1)
      set(ALSOFT_FORCE_ALIGN        "__attribute__((force_align_arg_pointer))")
    endif()

    if(_GEN_OPENAL_ANDROID_ABI STREQUAL "x86_64")
      set(HAVE_SSE                  1)
      set(HAVE_SSE2                 1)
      set(HAVE_SSE3                 1)
      set(HAVE_SSE4_1               1)
      set(HAVE_SSE_INTRINSICS       1)
    endif()

    if(_GEN_OPENAL_ANDROID_ABI STREQUAL "arm64-v8a")
      set(HAVE_NEON                 1)
    endif()

  endif()

  if("${_GEN_OPENAL_GENERATED_PLATFORM_DIR}" STREQUAL "")
    message(FATAL_ERROR "[ GEN OpenAL] Unsupported platform selection for OpenAL Soft 1.24.3")
  endif()

  file(MAKE_DIRECTORY "${_GEN_OPENAL_GENERATED_PLATFORM_DIR}")

  configure_file("${_GEN_OPENAL_TEMPLATES_DIR}/config.h.in"          "${_GEN_OPENAL_GENERATED_PLATFORM_DIR}/config.h"          @ONLY)
  configure_file("${_GEN_OPENAL_TEMPLATES_DIR}/config_backends.h.in" "${_GEN_OPENAL_GENERATED_PLATFORM_DIR}/config_backends.h" @ONLY)
  configure_file("${_GEN_OPENAL_TEMPLATES_DIR}/config_simd.h.in"     "${_GEN_OPENAL_GENERATED_PLATFORM_DIR}/config_simd.h"     @ONLY)
  configure_file("${_GEN_OPENAL_TEMPLATES_DIR}/version.h.in"         "${_GEN_OPENAL_GENERATED_PLATFORM_DIR}/version.h")

  list(PREPEND GEN_INCLUDES_DIR_LIST "${_GEN_OPENAL_TEMPLATES_DIR}/fmt-11.1.1/include")
  list(PREPEND GEN_INCLUDES_DIR_LIST "${_GEN_OPENAL_TEMPLATES_DIR}/common")
  list(PREPEND GEN_INCLUDES_DIR_LIST "${_GEN_OPENAL_GENERATED_PLATFORM_DIR}")

  set(GEN_TPL_SOURCES)

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/auxeffectslot.cpp")    
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/buffer.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/debug.cpp")  
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/error.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/event.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effect.cpp")   
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/extension.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/filter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/listener.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/source.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/state.cpp")

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/autowah.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/chorus.cpp")    
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/compressor.cpp")   
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/convolution.cpp")   
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/dedicated.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/distortion.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/echo.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/effects.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/equalizer.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/fshifter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/modulator.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/null.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/pshifter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/reverb.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/effects/vmorpher.cpp")

  if(COMPILE_FOR_WINDOWS)  

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/eax/api.cpp")   
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/eax/call.cpp")   
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/eax/exception.cpp")    
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/eax/fx_slot_index.cpp")    
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/eax/fx_slots.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/al/eax/utils.cpp")

  endif()

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/alc.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/alu.cpp")    
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/alconfig.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/context.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/device.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/events.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/panning.cpp")

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/base.cpp")    
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/loopback.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/null.cpp")

  if(COMPILE_FOR_WINDOWS)  

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/winmm.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/dsound.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/wasapi.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/wave.cpp")

  endif()

  if(COMPILE_FOR_LINUX)  
  
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/alsa.cpp")	
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/oss.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/pulseaudio.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/wave.cpp")

  endif()

  if(COMPILE_FOR_ANDROID)

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/opensl.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/backends/wave.cpp")

  endif()

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/autowah.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/chorus.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/compressor.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/convolution.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/dedicated.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/distortion.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/echo.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/equalizer.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/fshifter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/modulator.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/null.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/pshifter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/reverb.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/alc/effects/vmorpher.cpp")

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/alassert.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/alcomplex.cpp") 
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/alsem.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/alstring.cpp")  
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/althrd_setname.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/dynload.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/filesystem.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/pffft.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/polyphase_resampler.cpp")      
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/ringbuffer.cpp")     
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/common/strutils.cpp")

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/ambdec.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/ambidefs.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/bformatdec.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/bs2b.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/bsinc_tables.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/buffer_storage.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/context.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/converter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/cpu_caps.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/cubic_tables.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/devformat.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/device.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/effectslot.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/except.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/filters/biquad.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/filters/nfc.cpp")   
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/filters/splitter.cpp")   
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/fpu_ctrl.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/helpers.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/hrtf.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/logging.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mastering.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/storage_formats.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/uhjfilter.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/uiddefs.cpp")
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/voice.cpp")

  if(COMPILE_FOR_LINUX)  

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/dbus_wrap.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/rtkit.cpp")

  endif()

  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer/mixer_c.cpp")

  if(COMPILE_FOR_WINDOWS OR COMPILE_FOR_LINUX_INTEL_64 OR _GEN_OPENAL_ANDROID_ABI STREQUAL "x86" OR _GEN_OPENAL_ANDROID_ABI STREQUAL "x86_64")

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer/mixer_sse.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer/mixer_sse2.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer/mixer_sse3.cpp")
    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer/mixer_sse41.cpp")

  endif()

  if(COMPILE_FOR_LINUX_ARM        OR      
     COMPILE_FOR_LINUX_ARM_64     OR
     COMPILE_FOR_LINUX_ARM_RPI    OR 
     COMPILE_FOR_LINUX_ARM_RPI_64 OR
     _GEN_OPENAL_ANDROID_ABI STREQUAL "arm64-v8a")    

    list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_OPENAL}/core/mixer/mixer_neon.cpp")

  endif()  

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(OpenAL ${GEN_TPL_SOURCES})
      
endif()


if(COMPILE_FOR_WINDOWS)

  if(WINDOWS_STACKWALKER_FEATURE)

    list(APPEND GEN_THIRDPARTY_LIBRARYS StackWalker)

    remove_definitions(-DUNICODE)   
    list(APPEND GEN_SOURCES_MODULES_LIST "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_STACKWALKER}/StackWalker.cpp")

  endif()

endif()


if(GOOGLETEST_FEATURE)

  add_definitions(-DGOOGLETEST_ACTIVE)

  list(APPEND GEN_THIRDPARTY_LIBRARYS GoogleTest)

  # GoogleTest requires at least C++14
  set(CMAKE_CXX_STANDARD 14)

  enable_testing()
  include(GoogleTest)
  set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)

  set(GEN_TPL_SOURCES)
  list(APPEND GEN_TPL_SOURCES "${GEN_DIRECTORY_THIRDPARTYLIBRARIES_GOOGLETEST_SOURCES}/gtest-all.cc")

  list(APPEND GEN_SOURCES_MODULES_LIST ${GEN_TPL_SOURCES})
  GEN_ThirdPartyLibraries_SuppressWarnings(GoogleTest ${GEN_TPL_SOURCES})

endif()
